version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: soa_node_backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - .env
    networks:
      - soa_shared_network

networks:
  soa_shared_network:
    external: true